### ISSUE TITLE
Grammar is in an endless loop - Grammar pushed the same rule without advancing error in editor

### ISSUE THREAD

**Issue by aeschli** [atom/language-java#151] opened 2018-08-15 16:47 UTC
_From @kittaakos on July 31, 2018 18:29_

 

- VSCode Version:
Version 1.26.0-insider (1.26.0-insider)
0707dd4940b3fdbea8339595de478f354f6dda83
2018-07-31T05:05:43.344Z

- OS Version:
OS X 10.13.5

Steps to Reproduce:
1. Create a file with  `.java` file extension. (Note, I do not have any VS Code Java extensions installed.)
```java
public class C {
    int i;
}
```

2. Set the cursor to the `<|>` position:
```java
public class C {
    <|>int i;
}
```

3. Type any non-whitespace character.

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2883 [2] - Grammar is in an endless loop - Grammar pushed the same rule without advancing
scanNext @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2883
_tokenizeString @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2814
Grammar._tokenize @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2570
Grammar.tokenizeLine2 @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2540
e.tokenize2 @ TMSyntax.ts:448
e._updateTokensUntilLine @ textModelTokens.ts:416
e._tokenizeOneLine @ textModelTokens.ts:379
f._revalidateTokensNow @ textModel.ts:1946
(anonymous) @ textModel.ts:1920
setTimeout (async)
f._beginBackgroundTokenization @ textModel.ts:1918
f._applyEdits @ textModel.ts:1388
f.applyEdits @ textModel.ts:1270
e.pushEditOperation @ editStack.ts:169
f._pushEditOperations @ textModel.ts:1263
f.pushEditOperations @ textModel.ts:1172
e._innerExecuteCommands @ cursor.ts:674
e.executeCommands @ cursor.ts:632
t._executeEditOperation @ cursor.ts:362
t._type @ cursor.ts:567
t.trigger @ cursor.ts:492
t.trigger @ codeEditorWidget.ts:873
t.runCommand @ coreCommands.ts:1701
handler @ editorExtensions.ts:105
e.invokeFunction @ instantiationService.ts:57
t._tryExecuteCommand @ commandService.ts:61
(anonymous) @ commandService.ts:50
then @ winjs.base.js:1587
t.executeCommand @ commandService.ts:50
type @ codeEditorWidget.ts:1387
e.type @ viewController.ts:80
(anonymous) @ textAreaHandler.ts:264
e.fire @ event.ts:140
(anonymous) @ textAreaInput.ts:272
```

Below is the bare minimum example that still throws the same error. Although, it is not a valid syntax.
```
{
    int i;
}
```

Does this issue occur when all extensions are disabled?: Yes.

_Copied from original issue: Microsoft/vscode#55497_

**Comment by aeschli** [comment] 2018-08-15 16:47
_From @alexandrudima on August 2, 2018 9:20_

:+1: Here is the minimal repro I could extract:
```java
class C {
    1int i;
}
```

`[2] - Grammar is in an endless loop - Grammar pushed the same rule without advancing` indicates that the grammar entered and left a begin/end rule without consuming anything, thus making an endless loop. The interpreter has broken the loop, but it still remains a mistake in the grammar.

**Comment by aeschli** [comment] 2018-08-15 16:47
_From @alexandrudima on August 2, 2018 9:20_

We could improve `vscode-textmate` to print the problematic rule...

**Comment by sadikovi** [comment] 2018-08-16 07:56
Thanks for reporting @aeschli. I will have a look shortly.

**Comment by sadikovi** [comment] 2018-08-17 06:49
@aeschli I can't reproduce it in master branch in Atom following the steps above. Are you sure it is language-java issue? Stacktrace does not contain any reference to the package.

**Comment by sadikovi** [comment] 2018-08-17 06:51
Sure, scope and highlighting are incorrect after adding a non-whitespace character, but I have not observed any endless loop.

**Comment by Ben3eeE** [comment] 2018-08-17 09:12
@sadikovi We have had similar reports before and it has been because of the vscode textmate engine and not something we can reproduce in Atom. See https://github.com/atom/language-c/issues/218 for example.

**Comment by sadikovi** [comment] 2018-08-17 09:16
Thanks @Ben3eeE! I almost started feeling a bit anxious that I can't reproduce it by following the steps in the description. I am going to close this then.

**Comment by Aerijo** [comment] 2018-08-17 09:34
@alexandrudima @sadikovi https://regex101.com/r/Hx8uxj/1/

**Comment by sadikovi** [comment] 2018-08-17 10:01
@Aerijo what do you mean by "it calls itself recursively"? Did you mean "repeated"? Your regex is not exactly match to what we use in the package, it should be something like this:

PCRE: `(?=((void|boolean|byte|char|short|int|float|long|double)|(?>(\w+\.)*[A-Z]+\w*))(<[\w<>,\.?\s\[\]]*>)?((\[\])*)?\s+[A-Za-z_$][\w$]*([\w\[\],$][\w\[\],\s]*)?\s*(=|;))`

Plus, I am still not seeing a problem. Those 2 occurrences of `int` is wrapping of 2 groups.

**Comment by aeschli** [comment] 2018-08-17 10:09
I verified that we are on the latest.
IMO the problem is with the `"variables"` rule, which only consists of lookaheads.
That rule matches as it looks for the occurrence of `int` without making that sure that this is a separate word. But no progress is made as none of the nested rules match. Then the `end` matches (again just a lookahead). And then the same rule variables matches again.

Atom doesn't warn on that, but it's not a good thing to have.

The fix is to add word boundries: `\\b(void|boolean|byte|char|short|int|float|long|double)\\b`

**Comment by sadikovi** [comment] 2018-08-17 10:12
@aeschli Can you verify that Atom also has this problem, even though it does not warn on it?

**Comment by aeschli** [comment] 2018-08-17 10:17
Atom:

![image](https://user-images.githubusercontent.com/6461412/44261224-504d7080-a217-11e8-95a0-7626933ba215.png)
![image](https://user-images.githubusercontent.com/6461412/44261242-5a6f6f00-a217-11e8-8497-425a3edecfde.png)
You can see that also Atom fails to highlight after a type name that ends with `int` but is fine any other other identifierr.

**Comment by Aerijo** [comment] 2018-08-17 10:26
@sadikovi 

> what do you mean by "it calls itself recursively"?

I meant that the rule calls itself recursively, because it's patterns form a path back to itself. This is an issue when the match is 0-width. If that's more repeated than recursive, sorry, I wasn't being precise.


> I could be wrong, but so far, I am not seeing any hints on endless loops there.

Debugging Atom and breaking on [this line](https://github.com/atom/first-mate/blob/master/src/grammar.coffee#L176) will show it. No error is emitted when this happens.

> int a = matches perfectly fine

Yes, the issue is when we try to write something before the "int" part

**Comment by sadikovi** [comment] 2018-08-17 10:37
Could you paste a stack trace or an error when debugging from when we write something before the “int” part? So far you have shown the correct example. Thanks.

**Comment by sadikovi** [comment] 2018-08-17 10:48
@aeschli can you confirm that your suggested fix works in VSCode?

My concern that even if it is an issue, we have to fix every similar occurrence in the package - would be good to come up with some sort of reproducer, so we can unittest it.

**Comment by Aerijo** [comment] 2018-08-17 10:50
@sadikovi 
With the following text
```
public class C {
    aint i;
}
```

I get this custom error

<img width="773" alt="screen shot 2018-08-17 at 8 44 17 pm" src="https://user-images.githubusercontent.com/22167388/44262430-63376380-a25e-11e8-853e-fd822675e4d2.png">

This can be reproduced by setting a breakpoint like so in a dev build of Atom (corresponding to the CoffeeScript line I link to above)
<img width="758" alt="screen shot 2018-08-17 at 8 46 19 pm" src="https://user-images.githubusercontent.com/22167388/44262501-a1cd1e00-a25e-11e8-8f2f-81b84b43fc4a.png">


There is no proper stack trace or error to provide, because the issue is silently ignored in Atom.

**Comment by aeschli** [comment] 2018-08-17 10:59
Yes, I verified my change in VSCode. There's no longer an endless loop.

There's still no type scope emitted for the identifier (`aint`). Uppercase identifiers are working (`Aint`)

**Comment by sadikovi** [comment] 2018-08-17 11:01
As far as I can tell based on your images, error case is handled, not
ignored. How does VSCode handle the same case?

**Comment by sadikovi** [comment] 2018-08-17 11:03
I am a bit confused. Not having scope and having an endless loop are two
separate issues. Which one are you pointing out to?

**Comment by aeschli** [comment] 2018-08-17 11:04
@sadikovi Yes, sorry, not having a scope is a different issue.

**Comment by Aerijo** [comment] 2018-08-17 11:37
OK. To be clear, all my input has been with regards to the original issue (`Grammar is in an endless loop - Grammar pushed the same rule without advancing error in editor`). 

From what I can tell, this grammar enters a loop when you follow the reproduction steps in the original post. My input has been to show why and where this is happening.

There are also two perspectives on this:

> As far as I can tell based on your images, error case is handled, not
ignored

- @sadikovi thinks this is an issue with the TextMate (VS Code) engine, and not the grammar. Atom popping the rule when it repeats itself is _handling_ it, not _ignoring_ it.

> the endless loop is always caused by catastrophic backtracking in a specific regular expression and not by engine differences

> Atom doesn't warn on that, but it's not a good thing to have.

- @alexandrudima & @aeschli think this is an issue with the grammar, and not the TextMate (VS Code) engine. Requiring the engine to pop this rule is exceptional, and is a valid concern with the grammar definition.


Did I miss anything related to this issue?


(Also,
> How does VSCode handle the same case?

Similar to Atom, but louder & stops applying new rules)

**Comment by sadikovi** [comment] 2018-08-17 11:51
I am not against fixing it, but there must a reproducible case that we add a unit test for. Plus, there could be other cases similar to this one. Anyway, @aeschli, feel free to open a PR, since it relates to VSCode , it’s not reproducible in Atom and you have a good understanding on how to fix it.

**Comment by lee-dohm** [comment] 2018-08-21 18:16
There's a lot here but from what I can see:

1. This does not reproduce in Atom (or while it reproduces, it does not cause buggy behavior because Atom's TextMate-derived grammar system handles the error)
1. The only objection to this with regard to Atom is that it would be more technically correct to change the grammar to not have this behavior

Given the above, I don't see any motivation for us to invest time in fixing this. Because of that, we believe that closing the issue is the correct course of action. If @aeschli wants to submit a PR that improves the situation for VSCode, we would evaluate that PR on its own merits.

**Comment by sadikovi** [comment] 2018-08-21 21:26
Thanks @lee-dohm. My point was that we could not unit test the fix inside the grammar, but as long as people can open a PR and verify that it works in VSCode, I am more than happy to merge the fix ASAP! Thanks @Aerijo for great follow-up and summary.

**Closed by sadikovi** 2018-08-21 21:26 UTC
Labels: wontfix

**Comment by aeschli** [comment] 2018-08-22 08:10
> it does not cause buggy behavior because Atom's TextMate-derived grammar system handles the error)
As you can see from the screenshot, the problem causes the rest of the line to not get any highlighting...

I created #151

**Comment by sadikovi** [comment] 2018-08-22 08:15
Yes, it won't, because it does not match the begin pattern, so the rest is ignored - it is not really a buggy behaviour.

**Comment by aeschli** [comment] 2018-08-22 08:19
Even the next statements don't get any highlighting...

![image](https://user-images.githubusercontent.com/6461412/44451754-e78a3d80-a5f4-11e8-9615-e8d75d0fcd9e.png)

**Comment by sadikovi** [comment] 2018-08-22 08:30
Yes, you are right - it is a bug! Your patch seems to fix it, thanks.

P.S. I am going to open another PR to add test for this issue. I would appreciate if the next time you could open an issue with a reproducer like the last image and that relates to the grammar, not some VSCode error.
