### ISSUE TITLE
Inline classes not detected if bracket is on another line

### ISSUE THREAD

**Issue by Victorystick** [atom/language-java#32] opened 2016-04-05 12:37 UTC
For example:

``` java
class AClass {
  public void someMethod() {
    // compare
    method( new Foo()
      {
        void bar( int a, int b ) {
          // ...
        }
      });

    // with
    method( new Foo() {
      void bar( int a, int b ) {
        // ...
      }
    });
  }
}
```

**Comment by 50Wliu** [comment] 2016-04-20 02:49
I cannot reproduce this using language-java@0.18.0; assuming fixed.

**Comment by 50Wliu** [comment] 2016-04-20 11:32
Forgot that I was on the `wl-new` branch which hasn't been merged yet :P.

**Closed** 2016-12-01 02:22 UTC
Labels: bug
