### ISSUE TITLE
Failed to load a language-java package grammar

### ISSUE THREAD

**Issue by cdiazr** [atom/language-java#94] opened 2017-05-17 14:10 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-java](https://github.com/atom/language-java) package 0.27.0

### Stack Trace

Failed to load a language-java package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\cdiaz\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-java\grammars\java server pages (jsp).json' in C:\Users\cdiaz\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-java\grammars\java server pages (jsp).json

Error: ENOENT: no such file or directory, open 'C:\Users\cdiaz\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-java\grammars\java server pages (jsp).json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/language-java/grammars/java server pages (jsp).json:1:1
```

### Commands

```
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.6.3 
atom-bootstrap3 1.2.12 
atom-typescript 11.0.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 1.7.25 
platformio-ide-terminal 2.5.0 
v-bootstrap4 0.1.8 
```

**Comment by 50Wliu** [comment] 2017-05-17 17:02
@cdiazr Is this error reproducible?  Can you navigate to `C:\Users\cdiaz\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-java\grammars\java server pages (jsp).json' in C:\Users\cdiaz\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-java\grammars\` and tell me the contents of that directory?

**Comment by stephen-last** [comment] 2017-05-18 20:51
I'm seeing these errors too. I've checked in `C:\Users\stephen.last\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-java\grammars`...

The file names seem to have `%20` instead of spaces, I'm guessing that's why these `ENOENT: no such file or directory` errors are showing. There are loads of them, and they popup every time I open Atom.

What should I do to fix this..?

**Comment by 50Wliu** [comment] 2017-05-18 21:12
@stephen-last This seems to be a rare occurrence.  Can you try reinstalling and see if that helps?

**Comment by jaygriz** [comment] 2017-05-19 17:00
I seem to be getting a series of similar errors.
hopping someone has an idea...

**Comment by jaygriz** [comment] 2017-05-19 17:31
in directory
>C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-java\grammars

there I find there four files:
> java%20server%20pages%20(jsp).json
> java.json
> javaproperties.json
> junit%20test%20report.json

**Comment by jaygriz** [comment] 2017-05-19 18:58
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-git](https://github.com/atom/language-git) package 0.19.0


### Stack Trace

Failed to load a language-git package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\me\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-git\grammars\git commit message.json' in C:\Users\me\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-git\grammars\git commit message.json

Error: ENOENT: no such file or directory, open 'C:\Users\me\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-git\grammars\git commit message.json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/language-git/grammars/git commit message.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
minimap 4.28.2 
```

**Comment by jaygriz** [comment] 2017-05-19 19:13
AtomSetup.exe
I just ran AtomSetup.exe with admin priv. Still get 17 red boxes

**Comment by stephen-last** [comment] 2017-05-19 20:48
I uninstalled Atom, then ran `AtomSetup-x64.exe` downloaded from https://atom.io/ and that fixed it for me, no errors.

**Comment by jaygriz** [comment] 2017-05-19 21:58
Thank you sir! 

that sounds reasonable

**Comment by Nollikino** [comment] 2017-05-25 15:06
It seems like when there was an update to 1.17.0 on Windows there are some problems where spaces weren't translated from "%20" to " " in file names.

All the files that had spaces in them in the grammars-directory seems to have had this problem on my end.

I wouldn't recommend it to anyone else, because it's a crude fix, but i issued this line in PowerShell, and it changed all the files to the correct version:
`PS C:\Users\<your username here>\AppData\Local\atom\app-1.17.1\resources\app\node_modules> ls .\language-*\grammars\* | rename-item -NewName {$_.name -replace "%20", " "}`

**Closed** 2018-09-25 19:42 UTC
Labels: more-information-needed, triaged, uncaught-exception
