### ISSUE TITLE
Java looks awful on Atom One syntax theme

### ISSUE THREAD

**Issue by taylorlapeyre** [atom/language-java#12] opened 2015-03-31 18:02 UTC
![or_mi7aan3oqjsk-riiq0fzianld-f4eg333bfd8oli](https://cloud.githubusercontent.com/assets/1610503/6925605/1f4e27fc-d7a6-11e4-8729-2e091c94738c.png)

Looks like words that aren't keywords, etc are colored yellow instead of white. I'm not sure if this is a language problem or a problem with Atom One - let me know if I should post this over there!

**Comment by thomasjo** [comment] 2015-03-31 22:19
Duplicate of https://github.com/atom/one-dark-syntax/issues/21.

**Closed by thomasjo** 2015-03-31 22:19 UTC
