### ISSUE TITLE
Syntax highlighting is broken with array syntax

### ISSUE THREAD

**Issue by Yanpas** [atom/language-java#227] opened 2020-04-29 15:29 UTC
### Prerequisites
I'm using vscode (https://github.com/microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json) and syntax version 2e179ceac423403eb5bf0eff26884093c3edba6f

### Description
Snippet:
```java
        for (int i = 0; i==0;){
            
        }
        String[] aaa = new String[] {
            String.class.toString(),
            "aaaa",
            "bbb",
        };
        for (int i = 0; i==0;){

        }
```
![image](https://user-images.githubusercontent.com/7345761/49146556-71902380-f313-11e8-910e-a7e642d590fa.png)

See also https://github.com/redhat-developer/vscode-java/issues/728

**Comment by sadikovi** [comment] 2020-09-06 07:08
Cannot reproduce on the master branch. This seems to have been fixed by https://github.com/atom/language-java/pull/215, at least, this is what git tells me, thus the version of vscode for which the bug was reported was likely using a different version of language-java package.

**Closed by sadikovi** 2020-09-06 07:08 UTC
