### ISSUE TITLE
Failed to load a language-java package grammar

### ISSUE THREAD

**Issue by jaymomnang** [atom/language-java#101] opened 2017-07-14 15:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-java](https://github.com/atom/language-java) package 0.27.1

### Stack Trace

Failed to load a language-java package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\meet_\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-java\grammars\junit test report.json' in C:\Users\meet_\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-java\grammars\junit test report.json

Error: ENOENT: no such file or directory, open 'C:\Users\meet_\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-java\grammars\junit test report.json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/language-java/grammars/junit test report.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-babel-compiler 2.3.1 
```

**Comment by 50Wliu** [comment] 2017-07-14 23:06
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/language-java#94. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-07-14 23:06 UTC
